# -*- coding: utf-8 -*-
"""newArchi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXpka3sLcy7spHdb3XywzSpQrejLot3t
"""

# =========================================================
# CELL 1 - IMPORTS
# =========================================================

import os
import copy
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error

from torch.utils.data import Dataset, DataLoader


# =========================================================
# REPRODUCIBILITY
# =========================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)

print("Device:", device)


# =========================================================
# SAVE PATH
# =========================================================

SAVE_DIR = "/content/drive/MyDrive/Colab Notebooks/Equation/saved_models"

os.makedirs(SAVE_DIR, exist_ok=True)

print("Models will save to:", SAVE_DIR)

# =========================================================
# CELL 2 - EQUATION
# =========================================================

def equation(x1, x2, x3, x4, x5):

    return (
        np.sin(5 * x1)
        + np.cos(5 * x2)
        + np.exp(-0.5 * np.abs(x3))
        + 0.3 * (x4 ** 2)
        + np.tanh(x1 * x5)
        + 0.5 * np.sin(x2 * x3)
    )

# =========================================================
# CELL 3 - DATA GENERATION
# =========================================================

N = 1_000_000

rng = np.random.default_rng(SEED)

X = np.column_stack([
    rng.uniform(-5, 5, N),
    rng.uniform(-5, 5, N),
    rng.uniform(-5, 5, N),
    rng.uniform(-5, 5, N),
    rng.uniform(-5, 5, N),
]).astype(np.float32)

y = equation(
    X[:, 0],
    X[:, 1],
    X[:, 2],
    X[:, 3],
    X[:, 4]
).reshape(-1, 1).astype(np.float32)

print("X Shape:", X.shape)
print("y Shape:", y.shape)

# =========================================================
# CELL 4 - TRAIN VALID TEST SPLIT
# =========================================================

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=SEED
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    random_state=SEED
)

print("Train:", X_train.shape)
print("Val  :", X_val.shape)
print("Test :", X_test.shape)

# =========================================================
# CELL 5 - SCALING
# =========================================================

x_scaler = StandardScaler()
y_scaler = StandardScaler()

X_train = x_scaler.fit_transform(X_train)
X_val = x_scaler.transform(X_val)
X_test = x_scaler.transform(X_test)

y_train = y_scaler.fit_transform(y_train)
y_val = y_scaler.transform(y_val)
y_test = y_scaler.transform(y_test)

# =========================================================
# CELL 6 - DATASET
# =========================================================

class RegressionDataset(Dataset):

    def __init__(self, X, y):

        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):

        return len(self.X)

    def __getitem__(self, idx):

        return self.X[idx], self.y[idx]

# =========================================================
# CELL 7 - DATALOADER
# =========================================================

train_loader = DataLoader(
    RegressionDataset(X_train, y_train),
    batch_size=4096,
    shuffle=True,
    pin_memory=True
)

val_loader = DataLoader(
    RegressionDataset(X_val, y_val),
    batch_size=4096,
    shuffle=False,
    pin_memory=True
)

test_loader = DataLoader(
    RegressionDataset(X_test, y_test),
    batch_size=4096,
    shuffle=False,
    pin_memory=True
)

# =========================================================
# CELL 8 - SIMPLE MLP (NO FOURIER FEATURES)
# =========================================================

class MLP(nn.Module):

    def __init__(self):

        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(5, 1024),
            nn.GELU(),

            nn.Linear(1024, 1024),
            nn.GELU(),

            nn.Linear(1024, 512),
            nn.GELU(),

            nn.Linear(512, 256),
            nn.GELU(),

            nn.Linear(256, 1)
        )

        self._init_weights()

    def _init_weights(self):

        for m in self.modules():

            if isinstance(m, nn.Linear):

                nn.init.xavier_normal_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, x):

        return self.net(x)

# =========================================================
# CELL 9 - TRAIN FUNCTION
# =========================================================

def train_model(model, name):

    model = model.to(device)

    criterion = nn.MSELoss()

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=1e-3,
        weight_decay=1e-6
    )

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=0.5,
        patience=10
    )

    best_val_loss = float("inf")

    patience = 40
    counter = 0

    history = {
        "epoch": [],
        "train_loss": [],
        "val_loss": [],
        "lr": []
    }

    for epoch in range(1000):

        # =====================================================
        # TRAIN
        # =====================================================

        model.train()

        train_loss = 0.0

        for xb, yb in train_loader:

            xb = xb.to(device, non_blocking=True)
            yb = yb.to(device, non_blocking=True)

            optimizer.zero_grad()

            pred = model(xb)

            loss = criterion(pred, yb)

            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                1.0
            )

            optimizer.step()

            train_loss += loss.item() * xb.size(0)

        train_loss /= len(train_loader.dataset)

        # =====================================================
        # VALIDATION
        # =====================================================

        model.eval()

        val_loss = 0.0

        with torch.no_grad():

            for xb, yb in val_loader:

                xb = xb.to(device, non_blocking=True)
                yb = yb.to(device, non_blocking=True)

                pred = model(xb)

                loss = criterion(pred, yb)

                val_loss += loss.item() * xb.size(0)

        val_loss /= len(val_loader.dataset)

        scheduler.step(val_loss)

        current_lr = optimizer.param_groups[0]["lr"]

        # =====================================================
        # SAVE HISTORY
        # =====================================================

        history["epoch"].append(epoch + 1)
        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["lr"].append(current_lr)

        # =====================================================
        # PRINT
        # =====================================================

        print(
            f"{name} | "
            f"Epoch {epoch+1:03d} | "
            f"LR {current_lr:.7f} | "
            f"Train {train_loss:.8f} | "
            f"Val {val_loss:.8f}"
        )

        # =====================================================
        # SAVE BEST MODEL
        # =====================================================

        if val_loss < best_val_loss:

            best_val_loss = val_loss

            counter = 0

            # SAVE BEST MODEL EVERY TIME
            torch.save(
                {
                    "epoch": epoch + 1,
                    "model_state_dict": model.state_dict(),
                    "optimizer_state_dict": optimizer.state_dict(),
                    "val_loss": val_loss
                },
                f"{SAVE_DIR}/{name}_best.pth"
            )

            print(f"Best model updated at epoch {epoch+1}")

        else:

            counter += 1

        # =====================================================
        # EARLY STOPPING
        # =====================================================

        if counter >= patience:

            print("Early stopping triggered")

            break

    # =====================================================
    # SAVE HISTORY CSV
    # =====================================================

    history_df = pd.DataFrame(history)

    history_df.to_csv(
        f"{SAVE_DIR}/{name}_history.csv",
        index=False
    )

    print(f"History saved: {name}_history.csv")

    return model, history_df

# =========================================================
# CELL 10 - EVALUATION
# =========================================================

def evaluate(model):

    model.eval()

    preds = []
    trues = []

    with torch.no_grad():

        for xb, yb in test_loader:

            xb = xb.to(device)

            pred = model(xb)

            preds.append(pred.cpu().numpy())
            trues.append(yb.numpy())

    preds = np.concatenate(preds)
    trues = np.concatenate(trues)

    preds = y_scaler.inverse_transform(preds)
    trues = y_scaler.inverse_transform(trues)

    r2 = r2_score(trues, preds)

    mae = mean_absolute_error(trues, preds)

    return r2, mae

# =========================================================
# CELL 11 - TRAIN MODEL
# =========================================================

model = MLP()

model, history_df = train_model(
    model,
    "MLP"
)

# =========================================================
# CELL 12 - LOAD BEST MODEL
# =========================================================

best_checkpoint = torch.load(
    f"{SAVE_DIR}/MLP_best.pth",
    map_location=device
)

model.load_state_dict(
    best_checkpoint["model_state_dict"]
)

print("Best Epoch:", best_checkpoint["epoch"])
print("Best Val Loss:", best_checkpoint["val_loss"])

# =========================================================
# CELL 13 - FINAL EVALUATION
# =========================================================

r2, mae = evaluate(model)

print("\nFinal Test Results")
print(f"R2  : {r2:.8f}")
print(f"MAE : {mae:.8f}")

# =========================================================
# CELL 14 - PLOT LOSS
# =========================================================

plt.figure(figsize=(8, 5))

plt.plot(
    history_df["epoch"],
    history_df["train_loss"],
    label="Train Loss"
)

plt.plot(
    history_df["epoch"],
    history_df["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training History")

plt.legend()

plt.grid(True)

plt.show()

